name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v1
      with:
        name: gitlab-extension
        path: ./artifact/gitlab-extension.zip   
    
#npm test
      env:
        CI: true

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        # An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
        artifact: ./artifact/gitlab-extension.zip   # optional, default is 
        # An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
#         artifacts: # optional, default is 
        # The content type of the artifact. Defaults to raw
        artifactContentType: zip # optional, default is 
        # An optional body for the release.
#         body: # optional, default is 
        # An optional body file for the release. This should be the path to the file
#         bodyFile: # optional, default is 
        # An optional commit reference. This will be used to create the tag if it does not exist.
#         commit: # optional, default is 
        # Optionally marks this release as a draft release. Set to true to enable.
#         draft: # optional, default is 
        # An optional name for the release. If this is omitted the tag will be used.
#         name: # optional, default is 
        # An optional tag for the release. If this is omitted the git ref will be used (if it is a tag).
#         tag:  # optional, default is 
        # The Github token.
#         token: # default is 
