name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v1
      with:
        name: gitlab-extension
        path: ./artifact/gitlab-extension.zip   
    
#npm test
      env:
        CI: true

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.0
      with:
        # Note-worthy description of changes in release
#         body: # optional, default is empty
        # Path to load note-worthy description of changes in release from
#         body-path: # optional, default is empty
        # Gives the release a custom name
#         name: # optional, default is Name of tag
        # Creates a draft release
#         draft: # optional, default is false
        # Comma-delimited list of path globs for asset files to upload
        files: artifact/gitlab-extension.zip # optional, default is empty
